language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
install:
  - pip install -U pip setuptools
  - pip install 'flake8<3'
script:
  - python setup.py install
  - flake8 .
